name: 'slack-notify-release'
description: 'A simple GitHub action to post a Slack message when a new version is released.'
author: 'ajainvivek'

inputs:
  project_name:
    description: 'Project name to display'
    required: true
  github_token:
    description: 'GitHub token'
    required: true
  slack_token:
    description: 'Slack token'
    required: true
  channel_id:
    description: 'Channel ID'
    required: true
  repo_name:
    description: 'Repository name'
    required: false

outputs:
  status:
    description: 'The status of message sent'
  
runs:
  using: 'node16'
  main: 'dist/index.js'

branding:
  icon: 'activity'
  color: 'white'
